version: "3.6"

services:
      
  nodered:
    build:
      context: .
    image: gcr.io/clusterekaitz/gcis:nodered
    container_name: nodered
    ports:
      - 1880:1880
    volumes:
      - node-red-data:/data

volumes:
  node-red-data:
