apiVersion: v1
kind: PersistentVolume
metadata:
  name: system-model-data
  labels:
    type: local
spec:
  storageClassName: system-model-data
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/system_model"
