apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-sock
  labels:
    type: local
spec:
  storageClassName: docker-sock
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/docker.sock"