apiVersion: v1
kind: PersistentVolume
metadata:
  name: event-manager-data
  labels:
    type: local
spec:
  storageClassName: event-manager-data
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/event_manager"
