apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-triggerer
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: julencuadra/gcis-fog:event-triggerer
        imagePullPolicy: Always
        name: event-manager
        resources: {}
      restartPolicy: Always
      nodeSelector:
        node-role.kubernetes.io/master: "true"    # Para desplegarlo en el master
status: {}