apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-manager
  labels:
    ehu.gcis: dummy-event-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      ehu.gcis: dummy-event-manager
  template:
    metadata:
      labels:
        ehu.gcis: dummy-event-manager
    spec:
      containers:
      - image: julencuadra/gcis-fog:event-manager-v2
        imagePullPolicy: Always
        name: event-manager
        resources: {}
      restartPolicy: Always
      serviceAccountName: service-account-event-manager
      nodeSelector:
        node-role.kubernetes.io/master: "true"    # Para desplegarlo en el master
status: {}
