apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulated-application-event
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: ekhurtado/gcis-fog:component-controller-v4.2 #TODO modificar imagen con la que se construya.
        imagePullPolicy: Always
        name: simulated-application-event
        resources: {}
status: {}
