apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data
  labels:
    type: local
spec:
  storageClassName: mosquitto-data
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mosquitto/data"