apiVersion: v1
kind: PersistentVolume
metadata:
  name: exist-data
  labels:
    type: local
spec:
  storageClassName: exist-data
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/exist/data"