apiVersion: misrecursos.aplicacion/v1alpha4
kind: Aplicacion
metadata:
  name: aplicacion-de-prueba-kafka
spec:
  componentes:
    - name: productor
      image: julencuadra/componente:productor
      previous: none
      next: B
    - name: transformador
      image: julencuadra/componente:transformador
      previous: A
      next: C
  replicas: 1
  desplegar: true