apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mosquitto-log
  name: mosquitto-log
spec:
  storageClassName: mosquitto-log
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
