apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mosquitto-data
  name: mosquitto-data
spec:
  storageClassName: mosquitto-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
