apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mosquitto-config
  name: mosquitto-config
spec:
  storageClassName: mosquitto-config
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
