apiVersion: ehu.gcis.org/v1alpha1
kind: Assemblyline
metadata:
  name: assemblyline
spec:
  name: assemblyline
  deploy: True
  assets:
    - name: assembly-robot-1
      deploy: True
      applications:
        - name: acquisition
          deploy: True
          replicas: 1
          components:
            - name: source-mqtt-kafka
              image: ekaitzhara/source-v2:source-mqtt-kafka
              flowConfig:
                next:
                  - name: assembly-robot-1-acquisition-sink-exist
                    IFMHtopic: data-assembly-robot-1-acquisition-sink-exist
              customization:
                - "MQTT_TOPIC=Asset/assembly-station/11"
                - "MQTT_CLIENT_NAME=assembly-robot-1-acquisition-source-mqtt-kafka"
              permanent: False
            - name: sink-exist
              image: ekaitzhara/sink-v2:sink-exist
              flowConfig:
                previous:
                  - name: assembly-robot-1-acquisition-source-mqtt-kafka
                    IFMHtopic: data-assembly-robot-1-acquisition-sink-exist
              permanent: False
        - name: processing
          deploy: True
          replicas: 1
          components:
            - name: exist
              image: ekaitzhara/source-v2:source-exist
              flowConfig:
                next:
                  - name: process
                    IFMHtopic: data-process
              customization:
                - "MACHINE_ID=11"
              permanent: False
            - name: process
              image: ekaitzhara/processing-v2:assembly-station-v2.2
              flowConfig:
                previous:
                  - name: assembly-robot-1-processing-exist
                    IFMHtopic: data-process
                next:
                  - name: assembly-robot-1-processing-influx
                    IFMHtopic: data-processed-app1
              customization:
                - "LIMIT=72"
              permanent: True
            - name: influx
              image: ekaitzhara/sink-v2:sink-influx
              flowConfig:
                previous:
                  - name: process
                    IFMHtopic: data-processed-app1
              permanent: False  
    - name: assembly-robot-2
      deploy: True
      applications:
        - name: acquisition
          deploy: True
          replicas: 1
          components:
            - name: mqtt-kafka
              image: ekaitzhara/source-v2:source-mqtt-kafka
              flowConfig:
                next:
                  - name: assembly-robot-2-acquisition-sink-exist
                    IFMHtopic: data-assembly-robot-2-acquisition-sink-exist
              customization:
                - "MQTT_TOPIC=Asset/assembly-station/22"
                - "MQTT_CLIENT_NAME=assembly-robot-2-acquisition-source-mqtt-kafka"
              permanent: False
            - name: sink-exist
              image: ekaitzhara/sink-v2:sink-exist
              flowConfig:
                previous:
                  - name: assembly-robot-2-acquisition-mqtt-kafka
                    IFMHtopic: data-assembly-robot-2-acquisition-sink-exist
              permanent: False  
        - name: processing
          deploy: True
          replicas: 1
          components:
            - name: exist
              image: ekaitzhara/source-v2:source-exist
              flowConfig:
                next:
                  - name: process
                    IFMHtopic: data-process
              customization:
                - "MACHINE_ID=22"
              permanent: False
            - name: process
              image: ekaitzhara/processing-v2:assembly-station-v2.2
              flowConfig:
                previous:
                  - name: assembly-robot-2-acquisition-exist
                    IFMHtopic: data-process
                next:
                  - name: assembly-robot-2-acquisition-influx
                    IFMHtopic: data-processed-app2
              customization:
                - "LIMIT=74"
              permanent: True
            - name: influx
              image: ekaitzhara/sink-v2:sink-influx
              flowConfig:
                previous:
                  - name: process
                    IFMHtopic: data-processed-app2
              permanent: False  