apiVersion: ehu.gcis.org/v1alpha1
kind: Residence
metadata:
  name: dummy-residence
spec:
  name: dummy-residence
  deploy: True
  patients:
    - name: carlos-dummy-patient
      deploy: True
      applications:
        - name: dummy-app
          deploy: True
          replicas: 1
          components:
            - name: dummy-component
              image: julencuadra/gcis-fog:dummy-component
              flowConfig: #ignorar por ahora
                next:
                  - name: assembly-robot-1-acquisition-sink-exist
                    IFMHtopic: data-assembly-robot-1-acquisition-sink-exist
              customization:
                - "MQTT_TOPIC=Asset/assembly-station/11"
                - "MQTT_CLIENT_NAME=assembly-robot-1-acquisition-source-mqtt-kafka"
              permanent: False
              events:
                - name: dummy-event
                  actions:
                    - name: dummy-action
                      image: julencuadra/gcis-fog:dummy-action-image
                      customization:
                        - "CustomParameters"