apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: exist-data
  name: exist-data
spec:
  storageClassName: exist-data
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
