apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
  labels:
    type: local
spec:
  storageClassName: grafana-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/grafana"
