apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  labels:
    vol: grafana-storage
spec:
  storageClassName: grafana-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Mi