apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-data
  labels:
    type: local
spec:
  storageClassName: influx-data
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/influxdbv2"