apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-controlador-aplicaciones
  labels:
    app: app-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-controller
  template:
    metadata:
      labels:
        app: app-controller
    spec:
      containers:
      - name: app-controller
        image: imagen-controlador-aplicaciones
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 8M
          limits:
            cpu: 100m
            memory: 16M
      nodeSelector:
        node-type: multipass

